
version: '3.8'

services:
  authonomy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: ./authonomy start --reset
    volumes:
      - .:/app
      - ./config.yaml:/root/config.yaml
      - ./ssi/schema:/root/ssi/schema
      - ./web:/root/web
    networks:
      - ssi_network
    depends_on:
      - ssi
  ssi:
    container_name: ssi
    image: ghcr.io/tbd54566975/ssi-service:main
    ports:
      - "8080:3000"
    environment:
      - CONFIG_PATH=/app/config/test.toml
      - JAEGER_HTTP_URL=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
      - redis
    volumes:
      - ./ssi/config:/app/config
    networks:
      - ssi_network
      - universal-resolver
    links:
      - uni-resolver
  jaeger:
    image: jaegertracing/all-in-one:latest
    platform: "linux/amd64"
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - ssi_network
  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # This allows for data to not be persisted on new runs
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
    ports:
      - "6379:6379"
    networks:
      - ssi_network
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "9001:8081"
    networks:
      - ssi_network
  uni-resolver:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8088:8080"
    platform: "linux/amd64"
    networks:
      - universal-resolver
  driver-did-ion:
    image: identityfoundation/driver-did-ion:v0.8.1
    ports:
      - "8089:8080"
    platform: "linux/amd64"
    networks:
      - universal-resolver

networks:
  ssi_network:
  universal-resolver:
