// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/application/{app_did}/config": {
            "get": {
                "description": "Retrieve the configuration for a specific application.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Application Management"
                ],
                "summary": "Get application configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application DID",
                        "name": "app_did",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configuration retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/models.Config"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Application not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/applications": {
            "get": {
                "description": "Retrieves a list of all applications",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Application Management"
                ],
                "summary": "Get all applications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ApplicationResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new application with the given details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Application Management"
                ],
                "summary": "Create a new application",
                "parameters": [
                    {
                        "description": "Application to create",
                        "name": "application",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApplicationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/attach-policy": {
            "post": {
                "description": "Attaches a policy to an application using the provided application and issuer DID, and schema ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization Management"
                ],
                "summary": "Attach policy to application",
                "parameters": [
                    {
                        "description": "Application Policy Request",
                        "name": "appPolicy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ApplicationPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully attached policy",
                        "schema": {
                            "$ref": "#/definitions/models.ApplicationPolicyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth-provider": {
            "get": {
                "description": "Retrieves a list of all auth providers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication Management"
                ],
                "summary": "Get available auth providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AvailableProvider"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth-provider/link": {
            "post": {
                "description": "Links an OAuth provider to an application by its DID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication Management"
                ],
                "summary": "Link Authentication Provider",
                "parameters": [
                    {
                        "description": "Authentication Provider Details",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthProvider"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully linked provider",
                        "schema": {
                            "$ref": "#/definitions/models.AuthProvider"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth-provider/unlink": {
            "post": {
                "description": "Links an OAuth provider to an application by its DID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication Management"
                ],
                "summary": "UnLink Authentication Provider",
                "parameters": [
                    {
                        "description": "Authentication Provider Details",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully linked provider",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/create-policy": {
            "post": {
                "description": "Creates a new policy based on the provided schema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization Management"
                ],
                "summary": "Create a new policy",
                "parameters": [
                    {
                        "description": "Policy Schema",
                        "name": "schema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PolicySchemaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully created policy",
                        "schema": {
                            "$ref": "#/definitions/models.PolicySchemaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/policies": {
            "get": {
                "description": "Retrieves a list of all policies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization Management"
                ],
                "summary": "Get all policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PolicySchemaResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AppDetails": {
            "type": "object",
            "required": [
                "description",
                "email"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 10
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "models.ApplicationPolicyRequest": {
            "type": "object",
            "required": [
                "application_did",
                "credential",
                "issuer_did",
                "schema_id"
            ],
            "properties": {
                "application_did": {
                    "type": "string"
                },
                "credential": {
                    "type": "object",
                    "additionalProperties": true
                },
                "issuer_did": {
                    "type": "string"
                },
                "schema_id": {
                    "type": "string"
                }
            }
        },
        "models.ApplicationPolicyResponse": {
            "type": "object",
            "properties": {
                "application_did": {
                    "type": "string"
                },
                "credential_id": {
                    "type": "string"
                },
                "issuer_did": {
                    "type": "string"
                },
                "schema_id": {
                    "type": "string"
                }
            }
        },
        "models.ApplicationRequest": {
            "type": "object",
            "required": [
                "app_details",
                "app_name"
            ],
            "properties": {
                "app_details": {
                    "$ref": "#/definitions/models.AppDetails"
                },
                "app_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "models.ApplicationResponse": {
            "type": "object",
            "properties": {
                "app_details": {
                    "$ref": "#/definitions/models.AppDetails"
                },
                "app_did": {
                    "type": "string"
                },
                "app_name": {
                    "type": "string"
                }
            }
        },
        "models.AuthProvider": {
            "type": "object",
            "required": [
                "app_details",
                "app_did",
                "config"
            ],
            "properties": {
                "app_details": {
                    "$ref": "#/definitions/models.AvailableProvider"
                },
                "app_did": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/models.OAuthConfig"
                }
            }
        },
        "models.AvailableProvider": {
            "type": "object",
            "required": [
                "provider_name",
                "provider_protocol",
                "provider_type"
            ],
            "properties": {
                "provider_name": {
                    "type": "string"
                },
                "provider_protocol": {
                    "type": "string"
                },
                "provider_type": {
                    "description": "social, email, phone, etc",
                    "type": "string"
                }
            }
        },
        "models.Config": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/models.ApplicationResponse"
                },
                "auth": {
                    "$ref": "#/definitions/models.AuthProvider"
                },
                "cred": {
                    "$ref": "#/definitions/models.ApplicationPolicyResponse"
                },
                "sessionKey": {
                    "type": "string"
                }
            }
        },
        "models.JsonSchema": {
            "type": "object",
            "properties": {
                "$schema": {
                    "type": "string"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "required": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.OAuthConfig": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "redirect_url": {
                    "type": "string"
                }
            }
        },
        "models.PolicySchemaRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "schema": {
                    "$ref": "#/definitions/models.JsonSchema"
                }
            }
        },
        "models.PolicySchemaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schema": {
                    "$ref": "#/definitions/models.JsonSchema"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
